version: '3'
services:
  db_padrao:
    container_name: db_padrao
    image: mysql:8
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ~/db_padrao:/var/lib/mysql
    environment:
      MYSQL_DATABASE: db_padrao
      MYSQL_ROOT_PASSWORD: root
    logging:
      driver: "json-file"
      options:
        max-size: 500m
volumes:
  db_padrao: